test.1a01/test.1a01/polls/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    path('p/', login_required(views.PollList.as_view()), name='poll_list'),
    path('p/a/', login_required(views.PollCreate.as_view()), name='poll_add'),
    path('p/<int:pk>/', login_required(views.PollDetail.as_view()), name='poll_view'),
    path('p/<int:pk>/e/', login_required(views.PollUpdate.as_view()), name='poll_edit'),
    path('p/<int:pk>/d/', login_required(views.PollDelete.as_view()), name='poll_del'),
    path('p/<int:pk>/a/', login_required(views.QuestCreate.as_view()), name='quest_add'),
    path('q/<int:pk>/e/', login_required(views.QuestUpdate.as_view()), name='quest_edit'),
    path('q/<int:pk>/d/', login_required(views.QuestDelete.as_view()), name='quest_del'),
    path('c/', login_required(views.CustList.as_view()), name='cust_list'),
    path('c/<int:cid>/', login_required(views.CustVotes.as_view()), name='cust_votes'),
    path('c/<int:cid>/<int:pid>/', login_required(views.CustAnswers.as_view()), name='cust_answers'),
]

test.1a01/test.1a01/urls.py
"""Main urls"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('polls/', include("polls.urls")),
    path('rest/', include("rest.urls")),
]

test.1a01/test.1a01/polls/models.py
import json

from django.db import models
from django.urls import reverse


class Poll(models.Model):
    title = models.CharField(max_length=32, unique=True, verbose_name='Наименование')
    date0 = models.DateField(db_index=True, verbose_name='Дата начала')
    date1 = models.DateField(db_index=True, verbose_name='Дата окончания')
    comments = models.CharField(max_length=255, null=True, blank=True, verbose_name='Комментарии')

    def __str__(self):
        return self.title

    def get_absolute_url(self) -> str:
        return reverse('poll_view', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('pk',)
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'


class Quest(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, db_index=True, editable=True, verbose_name='Опрос')
    title = models.CharField(max_length=255, blank=False, verbose_name='Вопрос')
    mult = models.BooleanField(db_index=True, verbose_name='Multichoice',
                               help_text="&#9744;=radio, &#9745;=checkboxes")
    payload = models.TextField(null=True, blank=True, verbose_name='Варианты',
                               help_text="Empty: text answer, multiline text: radio/checkboxes (1 line == 1 item)")

    def __str__(self):
        return self.title

    def get_absolute_url(self) -> str:
        return reverse('poll_view', kwargs={'pk': self.poll.pk})

    def get_type(self) -> int:
        """Return type of record.
        :return: 0=str, 1=radio, 2=checkboxes
        """
        return 0 if not self.payload else (1 if not self.mult else 2)

    def get_char(self) -> str:
        """Get html type representation"""
        return ("&#9997;", "&#9872;", "&#9745;")[self.get_type()]

    def get_list(self) -> list:
        """Get payload as list"""
        return self.payload.split("\r\n") if self.payload else None

    class Meta:
        ordering = ('poll', 'pk')
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class Answer(models.Model):
    cust_id = models.PositiveIntegerField(db_index=True, verbose_name="Пользователь")
    quest = models.ForeignKey(Quest, on_delete=models.CASCADE, db_index=True, verbose_name='Вопрос')
    resume = models.CharField(max_length=255, null=False, blank=False, verbose_name="Ответ")

    def __str__(self):
        data = json.loads(self.resume)
        if qtype := self.quest.get_type():   # radio/checkboxes
            if qtype == 1:  # radio
                return self.quest.get_list()[data]
            else:           # checboxes
                return ','.join(list(self.quest.get_list()[i] for i in data))
        else:               # str
            return data

    class Meta:
        ordering = ('cust_id', 'quest')
        unique_together = (('cust_id', 'quest'),)
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

test.1a01/test.1a01/polls/views.py
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic import CreateView, UpdateView, DeleteView

from . import models

PAGE_SIZE = 25


class PollList(ListView):
    """List polls"""
    model = models.Poll
    # template_name = 'polls/poll_list.html'
    # paginate_by = PAGE_SIZE


class PollDetail(DetailView):
    """Poll details"""
    model = models.Poll
    # template_name = 'polls/poll_detail.html'


class PollCreate(CreateView):
    """Add new poll.
    FIXME: chk date1 >= date0
    """
    model = models.Poll
    fields = ['title', 'date0', 'date1', 'comments']
    # template_name = 'polls/poll_form.html'


class PollUpdate(UpdateView):
    """Edit poll.
    FIXME: chk date1 >= date0
    """
    model = models.Poll
    fields = ['title', 'date1', 'comments']
    # template_name = 'polls/poll_form.html'


class PollDelete(DeleteView):
    """Delete poll."""
    model = models.Poll
    # template_name = 'polls/poll_delete.html'
    success_url = reverse_lazy('poll_list')


class QuestCreate(CreateView):
    """Add new question to a poll."""
    model = models.Quest
    fields = ['title', 'mult', 'payload']
    poll_id = object = None  # helpers

    def dispatch(self, request, *args, **kwargs):
        self.poll_id = int(kwargs['pk'])
        return super().dispatch(request, args, kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.poll = models.Poll.objects.get(pk=self.poll_id)
        self.object.save()
        return super().form_valid(form)


class QuestUpdate(UpdateView):
    """Edit question"""
    model = models.Quest
    fields = ['title', 'mult', 'payload']


class QuestDelete(DeleteView):
    """Delete question."""
    model = models.Quest
    success_url = reverse_lazy('poll_list')

    def dispatch(self, request, *args, **kwargs):
        poll_id = models.Quest.objects.get(pk=kwargs['pk']).poll_id
        self.success_url = reverse_lazy('poll_view', args=[poll_id])
        return super().dispatch(request, args, kwargs)


class CustList(ListView):
    """List of customers voted."""
    template_name = 'polls/cust_list.html'

    def get_queryset(self):
        return set(models.Answer.objects.values_list('cust_id', flat=True))


class CustVotes(ListView):
    """List of customer's votes."""
    template_name = 'polls/cust_votes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cid'] = self.kwargs['cid']
        return context

    def get_queryset(self):
        return models.Poll.objects.filter(quest__answer__cust_id=self.kwargs['cid']).distinct()


class CustAnswers(ListView):
    """List of customer's answers for the poll."""
    template_name = 'polls/cust_answers.html'

    def get_queryset(self):
        cust_id = self.kwargs['cid']
        poll_id = self.kwargs['pid']
        return models.Answer.objects.filter(cust_id=cust_id, quest__poll_id=poll_id)

test.1a01/test.1a01/templates/polls/cust_answers.html
{% extends "base.html" %}
{% block body_main %}
    <h1> Answers: </h1>
    <ul>
    {% for object in object_list %}
        <li> {{ object.quest.title }}: {{ object }} </li>
    {% endfor %}
    </ul>
{% endblock %}

test.1a01/test.1a01/templates/polls/cust_list.html
{% extends "base.html" %}
{% block body_main %}
    <h1> Customer list </h1>
    {% for object in object_list %}
        <button type="button">
             <a href="{% url 'cust_votes' object %}"> {{ object }} </a>
        </button>
    {% endfor %}
{% endblock %}

test.1a01/test.1a01/templates/polls/cust_votes.html
{% extends "base.html" %}
{% block body_main %}
    <h1> Vote list of customer '{{ cid }}' </h1>
    <ul>
    {% for object in object_list %}
        <li> <a href="{% url 'cust_answers' cid object.pk %}"> {{ object }} </a> </li>
    {% endfor %}
    </ul>
{% endblock %}

test.1a01/test.1a01/templates/polls/poll_confirm_delete.html
{% extends "base.html" %}
{% block body_main %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

test.1a01/test.1a01/templates/polls/poll_detail.html
{% extends "base.html" %}
{% block body_main %}
    <h1>
        Poll: {{ object }} ({{ object.date0|date:"d/m/y" }}&hellip;{{ object.date1|date:"d/m/y" }})
        <a href="{% url 'poll_edit' object.pk %}" title="Edit"> <button type="button"> &#9998; </button> </a>
        <a href="{% url 'poll_del' object.pk %}" title="Delete"> <button type="button"> &times; </button> </a>
    </h1>
    <i> {{ object.comments|default_if_none:"&lt;no comments&gt;" }}</i>
    <h2> Questions: {{ object.quest_set.count }}</h2>
    <ul>
        {% for quest in object.quest_set.all %}
            <li>
                ({{ quest.pk }}) {{ quest.title }}
                <a href="{% url 'quest_edit' quest.pk %}" title="Edit"> <button type="button"> &#9998; </button> </a>
                <a href="{% url 'quest_del' quest.pk %}" title="Delete"> <button type="button"> &times; </button> </a>
                {% if quest.payload %}
                    <details>
                        <summary> {{ quest.get_char|safe }} </summary>
                        <ul>
                            {% for i in quest.get_list %}
                                <li> {{ i }} </li>
                            {% endfor %}
                        </ul>
                    </details>
                {% endif %}
            </li>
        {% endfor %}
        <li> <a href="{% url 'quest_add' object.pk %}" title="Add new"> <button type="button"> &plus; </button> </</a> </li>
    </ul>
{% endblock %}

test.1a01/test.1a01/templates/polls/poll_form.html
{% extends "base.html" %}
{% block body_main %}
    <h1> Add/edit poll: </h1>
    <form method="post">{% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Save">
    </form>
{% endblock %}

test.1a01/test.1a01/templates/polls/poll_list.html
{% extends "base.html" %}
{% block body_main %}
    <h1> Poll list </h1>
    <ul>
        {% for object in object_list %}
            <li>
                <a href="{{ object.get_absolute_url }}"> {{ object }} </a>
                {% if object.comments %} <i> ({{ object.comments }}) </i> {% endif %}
            </li>
        {% endfor %}
        <li> <a href="{% url 'poll_add' %}"> <button type="button"> &plus; </button> </a> </li>
    </ul>
{% endblock %}

test.1a01/test.1a01/templates/polls/quest_confirm_delete.html
{% extends "base.html" %}
{% block body_main %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

test.1a01/test.1a01/templates/polls/quest_form.html
{% extends "base.html" %}
{% block body_main %}
    <h1> Add/edit question: </h1>
    <form method="post">{% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Save">
    </form>
{% endblock %}